version: "3.8"

services:
  db:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=hello-spring
      - POSTGRESQL_DATABASE=inclusion
    volumes:
    - db:/bitnami/postgresql
  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://db:5432/inclusion?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "hello-spring"
      }'
      CRAC_FILES_DIR: /var/crac/
    volumes:
      - .m2:/root/.m2
      - crac:/var/crac
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local
  crac:
    driver: local