version: "3.8"

services:
  db:
    image: bitnami/mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=hello-spring
      - MYSQL_DATABASE=inclusion
    volumes:
    - db:/bitnami/mysql
  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/inclusion?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "hello-spring"
      }'
      CRAC_FILES_DIR: /var/crac/
    volumes:
      - .m2:/root/.m2
      - crac:/var/crac
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local
  crac:
    driver: local