spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver

org.springframework.cloud.bindings.boot.enable: true
logging.level.org.hibernate: DEBUG
