spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    #driver-class-name: org.postgresql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.allow-pool-suspension: true